common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from pybo.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),  # '/' 에 해당되는 path
]

pybo/urls.py
from django.urls import path

from .views import base_views, question_views

app_name = 'pybo'

urlpatterns = [
    # base
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),

    # question
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),

    path('completed/<int:question_id>/', base_views.completed, name='completed'),
  ]

common/models.py
from django.db import models

# Create your models here.

pybo/models.py
from django.db import models
from django.contrib.auth.models import User


class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=200, verbose_name='タイトル')
    content = models.TextField(verbose_name='内容')
    PUBLIC_METHOD_CHOICES = [
        ('time', '時刻公開'),
        ('immediate', 'すぐ公開'),
        ('hold', '保留'),
    ]
    public_method = models.CharField(
        max_length=20,
        choices=PUBLIC_METHOD_CHOICES,
        default='time',
        verbose_name='公開方式'
    )
    PUSH_CHOICES = [
        ('push-on', '通知する'),
        ('push-off', '通知しない'),
    ]
    push = models.CharField(
        max_length=20,
        choices=PUSH_CHOICES,
        default='push-on',
        verbose_name='プッシュ通知有無'
    )
    issued_date = models.DateTimeField(verbose_name='発信日時')
    expiry_date = models.DateTimeField(null=True, blank=True, verbose_name='満了日時')

    class Meta:
        verbose_name = 'お知らせ'
        verbose_name_plural = 'お知らせ'

    def __str__(self):
        return self.subject

    def get_push_display(self):
        return dict(self.PUSH_CHOICES).get(self.push)

    def get_public_display(self):
        return dict(self.PUBLIC_METHOD_CHOICES).get(self.public_method)

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserForm(UserCreationForm):
    email = forms.EmailField(label="Email")

    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields + ("email",)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Username'
        self.fields['password1'].label = 'Password'
        self.fields['password2'].label = 'Password confirmation'
        self.fields['email'].label = 'Email'

pybo/forms.py
from django import forms
from pybo.models import Question


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question  # 사용할 모델
        fields = ['subject', 'content', 'public_method',
                  'issued_date', 'expiry_date', 'push']  # QuestionForm에서 사용할 Question 모델의 속성
        labels = {
            'subject': 'タイトル',
            'content': '내용',
        }
widgets = {
            'public_method': forms.RadioSelect,
            'push': forms.RadioSelect,
            'issued_date': forms.DateTimeInput(format='%Y-%m-%d %H:%M'),
            'expiry_date': forms.DateTimeInput(format='%Y-%m-%d %H:%M'),
        }

common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm


def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404

from pybo.models import Question


def index(request):
    page = request.GET.get('page', '1')  # 페이지
    question_list = Question.objects.order_by('-issued_date')
    print(question_list)
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj}
    return render(request, 'pybo/question_list.html', context)


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)

def completed(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_completed.html', context)

pybo/views/question_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from pybo.forms import QuestionForm
from pybo.models import Question


@login_required(login_url='common:login')
def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user  # 현재 로그인한 사용자를 작성자로 설정
            question.save()
            question = Question.objects.order_by('-id').first()
            return redirect('pybo:completed', question.id)
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)


@login_required(login_url='common:login')
def question_modify(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('pybo:detail', question_id=question.id)
    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.modify_date = timezone.now()  # 수정일시 저장
            question.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = QuestionForm(instance=question)
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)


@login_required(login_url='common:login')
def question_delete(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('pybo:detail', question_id=question.id)
    question.delete()
    return redirect('pybo:index')

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>사이트 이름?</title>
    <link rel="icon" href="https://www.gngs.co.jp/img/top/logo_about.png" type="image/png">
</head>
<body>
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<!-- 네비게이션바 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}

{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- 자바스크립트 Start -->
{%  block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

templates/common/login.html
{% extends "base.html" %}
{% block content %}

 <div class="mx-auto p-2" style="width: 800px;">
      <div class="card container my-5">
      <div class="card-body">
      <div class="form-group">
<div class="container my-4 ">

    <form method="post" action="{% url 'common:login' %}">

        {% csrf_token %}

        <input type="hidden" name="next" value="{{ next }}">  <!-- 로그인 성공후 이동되는 URL -->
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">Username</label>
            <input type="text" class="form-control shadow-sm p-2 mb-3 bg-body-tertiary rounded" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password">Password</label>
            <input type="password" class="form-control shadow-sm p-2 mb-3 bg-body-tertiary rounded " name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">ログイン</button>

          <button type="button"  class="btn btn-success" onclick="location.href='https://google.com'" >Googleログイン</button>


    </form>
</div>
 </div>
{% endblock %}

templates/common/signup.html
{% extends "base.html" %}
{% block content %}
    <div class="mx-auto p-2" style="width: 800px;">
<div class="container my-5">

    <div class="card card container my-5">
      <div class="card-body">
      <div class="form-group">

    <form method="post" action="{% url 'common:signup' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-4">
            <label for="username">Username</label>
            <input type="text" class="form-control shadow-sm p-2 mb-3 bg-body-tertiary rounded " name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-4">
            <label for="password1">Password</label>
            <input type="password" class="form-control shadow-sm p-2 mb-3 bg-body-tertiary rounded" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="mb-4">
            <label for="password2">Confirm password</label>
            <input type="password" class="form-control shadow-sm p-2 mb-3 bg-body-tertiary rounded" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="mb-4">
            <label for="email">Email</label>
            <input type="text" class="form-control shadow-sm p-2 mb-3 bg-body-tertiary rounded" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary ">登録</button>
        <button type="submit" class="btn btn-secondary">キャンセル</button>
    </form>
</div>
    </div>
{% endblock %}

templates/form_errors.html
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    {% for error in form.non_field_errors %}  <!-- 넌필드 오류를 출력한다. -->
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/navbar.html
<nav class="navbar navbar-dark bg-primary shadow p-1 mb-1 bg-body-tertiary rounded">
  <!-- Navbar content -->
    <div class="container-fluid">
    <img src="https://www.gngs.co.jp/img/top/logo_about.png"  alt="Logo" width="30" height="25" class="d-inline-block align-text-top">

        <a class="navbar-brand " href="{% url 'pybo:index' %} " style="margin-right: 1400px;" >GOMS</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} [キャンセル]</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}">ログイン</a>
                    {% endif %}
                </li>
                <li>
                    {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:signup' %}">新規登録</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/pybo/question_completed.html
{% extends 'base.html' %}
{% block content %}
<body>
    <div class="container my-5">
       <div class="card">
            <div class="card-body">
                 <h4 style="text-align: center;">基本情報</h4>
                    <!-- message 표시 -->
                 {% if messages %}
                     <div class="alert alert-danger my-3" role="alert">
                          {% for message in messages %}
                          <strong>{{ message.tags }}</strong>
                          <ul><li>{{ message.message }}</li></ul>
                          {% endfor %}
                     </div>
                 {% endif %}
                        <!-- 질문 -->
                     <div class="row" style="margin-top:30px;">
                          <div class="col-1"></div>
                          <div class="col-2" style="text-align: center; font-weight: bold;">
                               <label>タイトル</label>
                          </div>
                          <div class="col-1"></div>
                          <div class="col-7">
                               <label>{{ question.subject }}</label>
                          </div>
                     </div>
                     <div class="row" style="margin-top:30px;">
                          <div class="col-1"></div>
                          <div class="col-2" style="text-align: center; font-weight: bold;">
                               <label>公開方式</label>
                          </div>
                          <div class="col-1"></div>
                          <div class="col-7">
                               <label>{{ question.get_public_display }}</label>
                          </div>
                     </div>
                     <div class="row" style="margin-top:30px;">
                          <div class="col-1"></div>
                          <div class="col-2" style="text-align: center; font-weight: bold;">
                               <label>発信日</label>
                          </div>
                          <div class="col-1"></div>
                          <div class="col-7">
                               <label>{{ question.issued_date }}</label>
                          </div>
                     </div>
                     <div class="row" style="margin-top:30px;">
                          <div class="col-1"></div>
                          <div class="col-2" style="text-align: center; font-weight: bold;">
                              <label>満了日</label>
                          </div>
                          <div class="col-1"></div>
                          <div class="col-7">
                               <label>{{ question.expiry_date }}</label>
                          </div>
                     </div>
                     <div class="row" style="margin-top:30px;">
                          <div class="col-1"></div>
                          <div class="col-2" style="text-align: center; font-weight: bold;">
                               <label>通知有無</label>
                          </div>
                          <div class="col-1"></div>
                          <div class="col-7">
                               <label>{{ question.get_push_display }}</label>
                          </div>
                     </div>
                     <div class="row" style="margin-top:30px;">
                          <div class="col-1"></div>
                          <div class="col-2" style="text-align: center; font-weight: bold;">
                               <label>内容</label>
                          </div>
                          <div class="col-1"></div>
                          <div class="col-7">
                               <label>{{ question.content }}</label>
                          </div>
                     </div>
            </div>
       </div>
       <div class="my-3" style="text-align: center;">
             {% if request.user == question.author %}
             <a href="{% url 'pybo:index' %}"
             class="btn btn-primary" style="margin-top:30px;">お知らせ一覧</a>
            {% endif %}
       </div>
    </div>
    {% endblock %}

</body>

templates/pybo/question_detail.html
{% extends 'base.html' %}
{% block content %}
<body>
    <div class="container my-5">
       <div class="card">
            <div class="card-body">
                 <h4 style="text-align: center;">基本情報</h4>
                    <!-- message 표시 -->
                 {% if messages %}
                     <div class="alert alert-danger my-3" role="alert">
                          {% for message in messages %}
                          <strong>{{ message.tags }}</strong>
                          <ul><li>{{ message.message }}</li></ul>
                          {% endfor %}
                     </div>
                 {% endif %}
                        <!-- 질문 -->
                     <div class="row" style="margin-top:30px;">
                          <div class="col-1"></div>
                          <div class="col-2" style="text-align: center; font-weight: bold;">
                               <label>タイトル</label>
                          </div>
                          <div class="col-1"></div>
                          <div class="col-7">
                               <label>{{ question.subject }}</label>
                          </div>
                     </div>
                     <div class="row" style="margin-top:30px;">
                          <div class="col-1"></div>
                          <div class="col-2" style="text-align: center; font-weight: bold;">
                               <label>公開方式</label>
                          </div>
                          <div class="col-1"></div>
                          <div class="col-7">
                               <label>{{ question.get_public_display }}</label>
                          </div>
                     </div>
                     <div class="row" style="margin-top:30px;">
                          <div class="col-1"></div>
                          <div class="col-2" style="text-align: center; font-weight: bold;">
                               <label>発信日</label>
                          </div>
                          <div class="col-1"></div>
                          <div class="col-7">
                               <label>{{ question.issued_date }}</label>
                          </div>
                     </div>
                     <div class="row" style="margin-top:30px;">
                          <div class="col-1"></div>
                          <div class="col-2" style="text-align: center; font-weight: bold;">
                              <label>満了日</label>
                          </div>
                          <div class="col-1"></div>
                          <div class="col-7">
                               <label>{{ question.expiry_date }}</label>
                          </div>
                     </div>
                     <div class="row" style="margin-top:30px;">
                          <div class="col-1"></div>
                          <div class="col-2" style="text-align: center; font-weight: bold;">
                               <label>通知有無</label>
                          </div>
                          <div class="col-1"></div>
                          <div class="col-7">
                               <label>{{ question.get_push_display }}</label>
                          </div>
                     </div>
                     <div class="row" style="margin-top:30px;">
                          <div class="col-1"></div>
                          <div class="col-2" style="text-align: center; font-weight: bold;">
                               <label>内容</label>
                          </div>
                          <div class="col-1"></div>
                          <div class="col-7">
                               <label>{{ question.content }}</label>
                          </div>
                     </div>
            </div>
       </div>
       <div class="my-3" style="text-align: center;">
            {% if request.user == question.author %}
            <a href="{% url 'pybo:question_modify' question.id  %}"
               class="btn btn-primary">修正</a>
            <a href="javascript:void(0)" class="delete btn btn-danger"
               data-uri="{% url 'pybo:question_delete' question.id  %}">削除</a>
            <a href="{% url 'pybo:index' %}"
               class="btn btn-secondary">キャンセル</a>
            {% endif %}
       </div>
    </div>
    {% endblock %}
    {% block script %}
    <script type='text/javascript'>
        const delete_elements = document.getElementsByClassName("delete");
        Array.from(delete_elements).forEach(function(element) {
             element.addEventListener('click', function() {
                   if(confirm("本当に削除しますか？")) {
                   location.href = this.dataset.uri;
                   }
             });
        });
    </script>
    {% endblock %}
</body>

templates/pybo/question_list.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}
    <nav class="navbar navbar-expand-lg bg-body-tertiary"  style="border-bottom:1px solid #dee2e6;">
    <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarNav" >
            <ul class="nav nav-underline">
                <li class="nav-item" >
                    <a class="nav-link" aria-current="page" href="{% url 'pybo:index' %}">ホーム</a> <!--홈-->
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'pybo:index' %}">お知らせ管理</a> <!--공지사항관리-->
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="row">
    <div class="col-2" style="border-right:1px solid #dee2e6;" >
        <ul class="nav flex-column nav-pills nav-fill" style="margin-right: 90px;">
            <li class="nav-item">
                <a class="nav-link " aria-current="page" href="{% url 'pybo:index' %}">お知らせ一覧</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'pybo:question_create' %}">お知らせ登録</a>
            </li>
        </ul>
    </div>
    <div class="col-9">
        <div class="container my-0">
        <nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
                <ol class="breadcrumb" >
                    <li class="breadcrumb-item"><a href="{% url 'pybo:index' %}">ホーム</a></li>
                    <li class="breadcrumb-item active" aria-current="page">お知らせ一覧</li>
                </ol>
            </nav>
            <div style="text-align:left; margin-top: 5px;">
                <div id="current_date" style="margin-top: 10px; text-align: end;">
                    <script>
                        date = new Date();
                        year = date.getFullYear();
                        month = ('0' + (date.getMonth() + 1)).slice(-2); // 월이 한 자리 수일 때 앞에 0 추가
                        day = ('0' + date.getDate()).slice(-2);
                        document.getElementById("current_date").innerHTML = year + "年" + month + "月" + day + "日";
                    </script>
                </div>
                <h5>お知らせ一覧</h5><!--공지등록-->
            </div>
         <div class="card container my-3">
      <div class="card-body">
      <div class="form-group">
            <table class="table">
                        <thead>
                            <tr class="text-center ">
                                <th>No</th>
                                <th style="width:30%">タイトル</th>
                                <th>公開方式</th>
                                <th>発信日</th>
                                <th>満了日</th>
                                <th>通知</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% if question_list %}
                        {% for question in question_list %}
                        <tr class="text-center">
                            <td>
                                <!--번호-->
                                {{ forloop.counter }}
                            </td>
                            <td class="text-start">
                                <a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a>
                                {% if question.answer_set.count > 0 %}
                                <span class="text-danger small mx-2">{{ question.answer_set.count }}</span>
                                {% endif %}
                            </td>
                            <td class="text-center"> <!-- 공개 방식 -->
                                {% if question.public_method == 'time' %}
                                    <span>時刻公開</span>
                                {% elif question.public_method == 'immediate' %}
                                    <span>すぐに公開</span>
                                {% elif question.public_method == 'hold' %}
                                    <span>保留</span>
                                {% else %}
                                    <span>保留</span>
                                {% endif %}
                            </td>
                            <td>{{ question.issued_date }}</td> <!-- 발신일 -->
                            <td>{{ question.expiry_date }}</td> <!-- 만료일 -->
                            <td class="text-center">
                                {% if question.push == 'push-on' %}
                                    <span>通知する</span>
                                {% elif question.push == 'push-off' %}
                                    <span>通知しない</span>
                                {% endif %}
                            </td> <!-- 통지 여부 -->
                        </tr>
                        {% endfor %}
                        {% else %}
                        <tr>
                            <td colspan="6">공지사항이 없습니다.</td>
                        </tr>
                        {% endif %}
                        </tbody>
                    </table>
            <!-- 페이징처리 시작 -->
            <ul class="pagination justify-content-center">
                <!-- 이전페이지 -->
                {% if question_list.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ question_list.previous_page_number }}">以前</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="#">以前</a>
                </li>
                {% endif %}
                <!-- 페이지리스트 -->
                {% for page_number in question_list.paginator.page_range %}
                {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
                {% if page_number == question_list.number %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                </li>
                {% else %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                </li>
                {% endif %}
                {% endif %}
                {% endfor %}
                <!-- 다음페이지 -->
                {% if question_list.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ question_list.next_page_number }}">次</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="#">次</a>
                </li>
                {% endif %}
            </ul>
            <!-- 페이징처리 끝 -->
            <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">質問の登録</a>
        </div>
    </div>
</div>
{% endblock %}